/**
 * BLiNX 2: Masters of Time & Space - Recompiled Game Entry Point
 *
 * This is the executable that hosts the recompiled game code, on Windows x64
 * and macOS arm64. Both hosts run the same boot sequence:
 *
 * 1. Install the crash handler (VEH on Windows, SIGBUS/SIGSEGV elsewhere)
 * 2. Load the original XBE file from disk
 * 3. Initialize the Xbox memory layout (map data sections to original VAs)
 * 4. Start the emulated APU (only with RECOMP_AC97_READY, on hosts that can
 *    service its MMIO faults: x86-64 Windows/Proton, POSIX arm64)
 * 5. Initialize the Xbox kernel replacement layer
 * 6. Set up game file paths for I/O redirection
 * 7. Initialize the kernel bridge (thunk table in Xbox memory)
 * 8. Initialize the stack pointer
 * 9. Call the game's original entry point (recompiled)
 *
 * Platform-specific code is confined to the host_* functions below; the boot
 * sequence itself is host_main() and is shared.
 *
 * The game-specific constants are BLINX2_ENTRY_POINT, BLINX2_XBE_PATH and
 * BLINX2_GAME_DIR below; report_fault() prints the crash diagnosis.
 *
 * XBE details (from the toolkit's xbe_parser):
 *   Title:       BLiNX 2: Masters Of Time & Space
 *   Title ID:    0x4D530065
 *   Base addr:   0x00010000
 *   Entry point: 0x0029A1DA
 *   Code size:   ~2875 KB (.text)
 *   Sections:    73 (most are embedded model/motion data: MDL*, MOT*, M##)
 *   Kernel imports: 121
 */

#include "recomp_env.h"

#if defined(_WIN32)
#include <windows.h>
#include <dbghelp.h>
#else
/* <signal.h> already provides ucontext_t and the Darwin mcontext; including
 * <ucontext.h> directly is an #error on macOS without _XOPEN_SOURCE. The NT
 * types used below (BOOL, LONG, CALLBACK...) come from the toolkit's kernel.h
 * through <xbox/xboxrecomp.h>. */
#include <signal.h>
#include <dlfcn.h>
#include <unistd.h>
#endif
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdarg.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>
#include "video_player.h"   /* xbox_HostWindowSetTitle, xbox_HostWindowMain */

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. The
 * host side then writes g_esp somewhere the generated code never reads, so the
 * guest starts with every register at zero and faults immediately, having
 * apparently ignored the setup that visibly ran. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
/* x87 and SSE state. Global for the same reason the volatile GPRs are: one
 * guest routine can lift to several C functions, so a value written in one
 * body is read in the next. Defined in xbox_memory_layout.c like the rest of
 * the register file. */
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * From the XBE header (the toolkit's xbe_parser: python3 -m tools.xbe_parser
 * game_files/default.xbe). The paths are relative to the working directory,
 * so run from the project root.
 */
#define BLINX2_ENTRY_POINT      0x0029A1DA  /* XBE entry point VA */
#define BLINX2_XBE_PATH         "game_files/default.xbe"
#define BLINX2_GAME_DIR         "game_files"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);

/* Recompiled entry point (generated by recomp pipeline) */
extern void xbe_entry_point(void);

/* Flat dispatch table builder (recomp_dispatch.c). Declared here because
 * main.c does not include recomp_types.h; MSVC accepted the implicit
 * declaration with a warning, C99 compilers such as Clang reject it. */
extern int recomp_dispatch_init(void);

/* ── Host capabilities ─────────────────────────────────────── */

/* Whether this host can service hardware-register (MMIO) faults: decode the
 * faulting instruction, emulate the access and step over it. The toolkit's
 * decoder (apu_hook_handle_mmio, mmio_decode.h) understands x86-64 host code
 * only, so on arm64 the faulting instruction is A64 and nothing can resume it. */
#if defined(_WIN32) && (defined(_M_X64) || defined(__x86_64__))
#define HOST_CAN_SERVICE_MMIO 1
#elif !defined(_WIN32) && defined(__aarch64__)
/* POSIX arm64: SIGBUS/SIGSEGV + ucontext, with the toolkit's A64 decoder
 * (apu_hook_handle_mmio_posix, mmio_decode_a64.h). */
#define HOST_CAN_SERVICE_MMIO 1
#define HOST_MMIO_POSIX 1
#else
#define HOST_CAN_SERVICE_MMIO 0
#endif

/* ── Crash reporting (shared by every host) ────────────────── */

/* Fault access kinds handed to report_fault. */
#define FAULT_READ     0
#define FAULT_WRITE    1
#define FAULT_UNKNOWN (-1)

/* Label for the host program counter in the [CRASH] line: the register's own
 * name, so the number can be pasted straight into a debugger. */
#if defined(__aarch64__) || defined(_M_ARM64)
#define HOST_PC_LABEL "PC"
#else
#define HOST_PC_LABEL "RIP"
#endif

/* All crash output goes through here.
 *
 * On POSIX this runs inside a signal handler, possibly while the faulting
 * thread holds stdio's lock, so it formats into a stack buffer and write()s
 * instead of going through fprintf. On Windows the VEH has always used
 * fprintf(stderr), and still does. */
static void crash_printf(const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
#if defined(_WIN32)
    vfprintf(stderr, fmt, ap);
#else
    {
        char buf[512];
        int n = vsnprintf(buf, sizeof(buf), fmt, ap);
        if (n > 0) {
            size_t len = (size_t)n < sizeof(buf) ? (size_t)n : sizeof(buf) - 1;
            ssize_t r = write(STDERR_FILENO, buf, len);
            (void)r;
        }
    }
#endif
    va_end(ap);
}

/* Name the host symbol containing pc, as "name+0xoff", or "<unknown>".
 *
 * Windows: dbghelp against the PDB (SymInitialize runs at install time).
 * Elsewhere: dladdr, which on macOS reads the executable's own symbol table --
 * static functions included, no -export_dynamic needed -- as long as the
 * binary is not stripped. dli_sname has no leading underscore. */
static void host_symbol_for(void *pc, char *out, size_t n)
{
#if defined(_WIN32)
    /* SYMBOL_INFO is variable-length: the name is written past the struct, so
     * it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)pc, &disp, sym)) {
        snprintf(out, n, "%s+0x%llX", sym->Name, (unsigned long long)disp);
        return;
    }
#else
    Dl_info info;

    if (dladdr(pc, &info) && info.dli_sname && info.dli_saddr) {
        snprintf(out, n, "%s+0x%lX", info.dli_sname,
                 (unsigned long)((uintptr_t)pc - (uintptr_t)info.dli_saddr));
        return;
    }
#endif
    snprintf(out, n, "<unknown>");
}

/* Name the guest function a fault happened in, and recover the call chain.
 *
 * Recompiled code faults as ordinary native code, so the fault carries a host
 * PC and nothing else -- there is no guest program counter to report, and the
 * host address changes every build. Two things recover the guest view:
 *
 *   - every generated function is a real symbol in the image (sub_005A03C0
 *     and so on), so the symbol table already maps host address back to guest
 *     function. host_symbol_for turns an anonymous PC into that name.
 *
 *   - every lifted call pushes its guest return address onto the guest stack
 *     before jumping, so the stack still holds the chain. Scanning up from esp
 *     for values inside the code sections recovers it.
 *
 * ponytail: the stack scan is a scan, not a frame walk -- these are FPO frames
 * with no reliable ebp chain, so there is nothing to walk. It over-reports,
 * since addresses from returned-from calls linger below esp, but naming the
 * guest function is the whole question at a fault.
 *
 * Requires an unstripped executable (and on Windows, the .pdb beside the .exe).
 */
static void print_guest_context(void *pc)
{
    char name[300];
    /* The scan reads 256 words up from esp. Only do that when the whole
     * window is inside mapped guest RAM: with a garbage esp the scan would
     * fault in the middle of the report and lose everything after it. */
    bool stack_ok = g_esp >= XBOX_BASE_ADDRESS
                    && (size_t)g_esp + 256 * 4 <= g_xbox_total_ram;

    host_symbol_for(pc, name, sizeof(name));
    crash_printf("  in %s\n", name);

    if (g_xbox_mem_offset) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        crash_printf("  guest stack (return addresses, innermost first):\n");
        for (i = 0; stack_ok && i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                crash_printf("    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
        /* When the frame is gone, say so, and fall back on what is left.
         *
         * A fault inside a block copy leaves no return address in range: the
         * copy is a host memmove and its caller's frame is further up than
         * this reaches. Worse, a copy that ran past its buffer overwrites the
         * stack itself, so the list comes out empty exactly when it is most
         * needed -- and an empty list under a promising heading reads like
         * "nothing to see" rather than "the evidence is destroyed". */
        if (!shown)
            crash_printf("    (no return addresses in range)%s\n",
                         stack_ok ? "" : " -- esp outside guest RAM, not read");

        /* Everything below only pays for itself when the scan came back
         * empty. A crash where the chain was recovered already says what
         * happened, and burying that under another twenty lines makes the
         * common report worse to read. */
        if (!shown) {
            uint32_t k;

            /* The indirect-call history, which the stack cannot overwrite.
             * recomp_manual.c prints this too, but only from
             * recomp_icall_fail_log -- a page fault inside a block copy
             * never reaches that path, and this is the same information by
             * the route the fault actually took.
             *
             * Declared here rather than included: main.c does not pull in
             * recomp_types.h, and recomp_manual.c spells it the same way. */
            extern volatile uint32_t g_icall_trace[16];
            extern volatile uint32_t g_icall_trace_idx;

            crash_printf("  recent ICALL targets:");
            for (k = 0; k < 16; k++)
                crash_printf(" %08X",
                             g_icall_trace[(g_icall_trace_idx + k) & 15]);
            crash_printf("\n");

            /* The frame unfiltered. The pointers and lengths handed to
             * whatever faulted live here and look nothing like code, so the
             * filter above drops exactly what is wanted. On the crash this
             * was written for, one of these words was the end of the mapped
             * RAM mirror -- which is what identified the fault as a copy
             * running off its buffer rather than a stray pointer. */
            for (i = 0; stack_ok && i < 20; i++)
                crash_printf("    raw[esp+%-4d] 0x%08X\n", i * 4, sp[i]);
        }
    }
}

/*
 * The host-independent part of a crash report: what faulted, the guest
 * registers, and the guest function and call chain. Each host's handler
 * decodes its own fault record, calls this, then appends its native stack.
 *
 * This is your primary debugging tool during bring-up. Customize it for your
 * game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 */
static void report_fault(void *host_pc, uintptr_t data_addr, int access)
{
    crash_printf("[CRASH] Access violation at " HOST_PC_LABEL "=0x%llX, fault addr=0x%llX (%s)\n",
        (unsigned long long)(uintptr_t)host_pc,
        (unsigned long long)data_addr,
        access == FAULT_WRITE ? "write"
        : access == FAULT_READ ? "read" : "unknown");
    crash_printf("  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
        g_eax, g_ecx, g_edx, g_esp);
    crash_printf("  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
        g_ebx, g_esi, g_edi);
    if (data_addr - (uintptr_t)g_xbox_mem_offset <= 0xFFFFFFFFu)
        crash_printf("  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(data_addr - (uintptr_t)g_xbox_mem_offset));
    else
        crash_printf("  Xbox VA of fault: (host address, outside guest memory)\n");
    print_guest_context(host_pc);
}

#if defined(_WIN32)

/* ── Windows: VEH crash handler ────────────────────────────── */

/* The emulated APU.
 *
 * Two entry points that had no callers anywhere in the tree. apu_mmio_hook.c
 * documents apu_hook_handle_mmio as "called from VEH in main.c" and no main.c
 * called it; apu_decode_and_handle's first line is `if (!g_apu_state) return
 * false` and nothing assigned g_apu_state. So with RECOMP_AC97_READY set the
 * APU's registers were unmapped to be trapped, and every trap was then
 * declined and surfaced as an access violation on the first register
 * DirectSound touched. The VEH below now reaches apu_hook_handle_mmio
 * through the toolkit's xbox_VehMmioFault.
 *
 * Declared rather than included so this does not depend on src/apu being on
 * the include path. */
typedef struct MCPXAPUState MCPXAPUState;
extern MCPXAPUState *mcpx_apu_init_standalone(uint8_t *ram_ptr);
extern MCPXAPUState *g_apu_state;

/* The exe's own address range, for picking return addresses out of the native
 * stack. Read from the loaded image rather than assumed: the linker's base is
 * 0x140000000, but Wine loaded the exe at 0x6FFFF5AF0000, so a fixed range
 * printed nothing there. Filled at install time. */
static uintptr_t g_image_lo, g_image_hi;

/* The last fault reported. Returning EXCEPTION_CONTINUE_SEARCH lets the
 * exception travel on, and the same fault comes back through this handler
 * (first chance, then again when it is dispatched a second time), which
 * printed every report twice. A different fault still gets its own report. */
static uintptr_t g_last_fault_pc, g_last_fault_addr;

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        /* Trapped hardware registers (APU, USB OHCI) -> their models, through
         * the toolkit's dispatch.
         *
         * The other half of RECOMP_AC97_READY: reporting the codec ready is
         * what lets DirectSoundCreate past its first gate, and from there it
         * drives the APU directly, so the registers have to fault to be seen.
         * "Handled" means the access was decoded and the instruction stepped
         * over, so execution resumes instead of unwinding. */
        if (xbox_VehMmioFault(ep))
            return EXCEPTION_CONTINUE_EXECUTION;

        if ((uintptr_t)ep->ContextRecord->Rip == g_last_fault_pc
                && fault_addr == g_last_fault_addr)
            return EXCEPTION_CONTINUE_SEARCH;
        g_last_fault_pc = (uintptr_t)ep->ContextRecord->Rip;
        g_last_fault_addr = fault_addr;

        report_fault((void *)ep->ContextRecord->Rip, fault_addr,
                     ep->ExceptionRecord->ExceptionInformation[0]
                         ? FAULT_WRITE : FAULT_READ);

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (return addrs in image %p-%p):\n",
                    (void *)g_image_lo, (void *)g_image_hi);
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= g_image_lo && sp[i] < g_image_hi) {
                    char name[300];
                    host_symbol_for((void *)sp[i], name, sizeof(name));
                    fprintf(stderr, "    [%d] 0x%llX in %s\n", i,
                            (unsigned long long)sp[i], name);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

static void host_install_crash_handler(void)
{
    /* Install VEH handler (first handler in chain) */
    /* Load symbols up front rather than from inside the handler: at fault
     * time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler prints no name. */
    HMODULE self = GetModuleHandleA(NULL);
    char dir[MAX_PATH];
    DWORD n;

    /* The image range for the native stack scan. */
    g_image_lo = (uintptr_t)self;
    g_image_hi = g_image_lo;
    {
        const IMAGE_DOS_HEADER *dos = (const IMAGE_DOS_HEADER *)self;
        if (dos && dos->e_magic == IMAGE_DOS_SIGNATURE) {
            const IMAGE_NT_HEADERS *nt = (const IMAGE_NT_HEADERS *)
                ((const uint8_t *)self + dos->e_lfanew);
            if (nt->Signature == IMAGE_NT_SIGNATURE)
                g_image_hi = g_image_lo + nt->OptionalHeader.SizeOfImage;
        }
    }

    /* Search the exe's own directory for the PDB. Under Wine, dbghelp did
     * not find the lld PDB from the default search path. */
    n = GetModuleFileNameA(self, dir, sizeof(dir));
    if (n > 0 && n < sizeof(dir)) {
        char *slash = strrchr(dir, '\\');
        char *fwd = strrchr(dir, '/');
        if (fwd > slash) slash = fwd;
        if (slash) *slash = '\0';
    } else {
        dir[0] = '\0';
    }

    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME);
    if (!SymInitialize(GetCurrentProcess(), dir[0] ? dir : NULL, TRUE))
        fprintf(stderr, "[BOOT] SymInitialize failed (error %lu);"
                " crash reports will not name symbols\n", GetLastError());
    else if (dir[0])
        SymSetSearchPath(GetCurrentProcess(), dir);
    AddVectoredExceptionHandler(1, veh_handler);
}

/* ── Windows: on-demand dump of every thread (RECOMP_THREAD_DUMP) ─
 *
 * There is no SIGUSR1 under Wine, and a debugger attach from the Linux side
 * sees Wine's unix stacks, not the PE ones. With RECOMP_THREAD_DUMP set, a
 * thread polls for the file thread_dump.trigger in the working directory
 * (the game dir: `touch` it from the host); when it appears it is deleted
 * and every other thread is suspended in turn, its context unwound with the
 * PE unwind tables (RtlVirtualUnwind), and resumed. Frames are collected
 * while the thread is suspended and printed only after it resumes, so a
 * thread suspended while holding the stdio lock cannot wedge the dump.
 * Lines: "[DUMP] tid N" then "    [i] 0x<addr>"; the addresses are runtime
 * ones (the image base is printed) for llvm-symbolizer offline. */
#include <tlhelp32.h>

#define DUMP_MAX_FRAMES 40

static int win_unwind(HANDLE th, DWORD64 *pcs, int max, DWORD64 *rsp0)
{
    CONTEXT ctx;
    int n = 0;

    memset(&ctx, 0, sizeof(ctx));
    ctx.ContextFlags = CONTEXT_FULL;
    if (!GetThreadContext(th, &ctx))
        return -1;
    *rsp0 = ctx.Rsp;
    while (n < max && ctx.Rip) {
        DWORD64 base = 0, frame = 0;
        PVOID hdata = NULL;
        PRUNTIME_FUNCTION fn;

        pcs[n++] = ctx.Rip;
        fn = RtlLookupFunctionEntry(ctx.Rip, &base, NULL);
        if (fn) {
            RtlVirtualUnwind(UNW_FLAG_NHANDLER, base, ctx.Rip, fn, &ctx,
                             &hdata, &frame, NULL);
        } else {
            /* Leaf function: the return address is at rsp. */
            if (!ctx.Rsp || (ctx.Rsp & 7))
                break;
            ctx.Rip = *(DWORD64 *)(uintptr_t)ctx.Rsp;
            ctx.Rsp += 8;
        }
    }
    return n;
}

static void win_dump_all_threads(void)
{
    DWORD me = GetCurrentThreadId(), pid = GetCurrentProcessId();
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPTHREAD, 0);
    THREADENTRY32 te;

    if (snap == INVALID_HANDLE_VALUE)
        return;
    fprintf(stderr, "[DUMP] begin; image %p-%p\n",
            (void *)g_image_lo, (void *)g_image_hi);
    if (g_xbox_mem_offset) {
        uint32_t dev = *(volatile uint32_t *)((uintptr_t)g_xbox_mem_offset + 0x2F1FB8);
        if (dev && dev + 0x40 <= g_xbox_total_ram) {
            uint32_t p30 = *(volatile uint32_t *)((uintptr_t)g_xbox_mem_offset + dev + 0x30);
            fprintf(stderr, "[DUMP] d3d device 0x%08X: +0x2C=0x%08X +0x30=0x%08X\n", dev,
                    *(volatile uint32_t *)((uintptr_t)g_xbox_mem_offset + dev + 0x2C), p30);
            if (p30 && p30 < g_xbox_total_ram)
                fprintf(stderr, "[DUMP]   *(+0x30)=0x%08X\n",
                        *(volatile uint32_t *)((uintptr_t)g_xbox_mem_offset + p30));
        }
    }
    if (g_apu_state) {
        extern uint64_t mcpx_apu_mmio_read(MCPXAPUState *d, uint64_t addr, unsigned int size);
        extern void xbox_IrqlDumpHolders(void);
        fprintf(stderr, "[DUMP] apu ISTS=0x%08X IEN=0x%08X FECTL=0x%08X FEDECMETH=0x%08X FEDECPARAM=0x%08X SECTL=0x%08X\n",
                (unsigned)mcpx_apu_mmio_read(g_apu_state, 0x1000, 4),
                (unsigned)mcpx_apu_mmio_read(g_apu_state, 0x1004, 4),
                (unsigned)mcpx_apu_mmio_read(g_apu_state, 0x1100, 4),
                (unsigned)mcpx_apu_mmio_read(g_apu_state, 0x1300, 4),
                (unsigned)mcpx_apu_mmio_read(g_apu_state, 0x1304, 4),
                (unsigned)mcpx_apu_mmio_read(g_apu_state, 0x2000, 4));
        xbox_IrqlDumpHolders();
    }
    te.dwSize = sizeof(te);
    if (Thread32First(snap, &te)) {
        do {
            DWORD64 pcs[DUMP_MAX_FRAMES], rsp = 0;
            HANDLE th;
            int n, i;

            if (te.th32OwnerProcessID != pid || te.th32ThreadID == me)
                continue;
            th = OpenThread(THREAD_SUSPEND_RESUME | THREAD_GET_CONTEXT |
                            THREAD_QUERY_INFORMATION, FALSE, te.th32ThreadID);
            if (!th)
                continue;
            if (SuspendThread(th) == (DWORD)-1) {
                CloseHandle(th);
                continue;
            }
            n = win_unwind(th, pcs, DUMP_MAX_FRAMES, &rsp);
            ResumeThread(th);
            CloseHandle(th);
            fprintf(stderr, "[DUMP] tid %lu rsp 0x%llX frames %d\n",
                    (unsigned long)te.th32ThreadID, (unsigned long long)rsp, n);
            for (i = 0; i < n; i++)
                fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)pcs[i]);
        } while (Thread32Next(snap, &te));
    }
    CloseHandle(snap);
    fprintf(stderr, "[DUMP] end\n");
    fflush(stderr);
}

static DWORD WINAPI thread_dump_main(LPVOID arg)
{
    (void)arg;
    for (;;) {
        Sleep(500);
        if (GetFileAttributesA("thread_dump.trigger") != INVALID_FILE_ATTRIBUTES) {
            DeleteFileA("thread_dump.trigger");
            win_dump_all_threads();
        }
    }
    return 0;
}

static void host_install_thread_dump(void)
{
    HANDLE t;

    if (!recomp_env(RENV_THREAD_DUMP))
        return;
    t = CreateThread(NULL, 0, thread_dump_main, NULL, 0, NULL);
    if (t) {
        CloseHandle(t);
        fprintf(stderr, "[BOOT] thread_dump: touch thread_dump.trigger in "
                        "the game dir to dump every thread\n");
    }
}

#else /* !_WIN32 */

/* ── POSIX: SIGBUS/SIGSEGV crash handler ───────────────────── */

/* Guest memory is reserved PROT_NONE, and on macOS touching a mapped but
 * inaccessible page is SIGBUS; only a truly unmapped address is SIGSEGV. So
 * the common guest fault arrives as SIGBUS, and both are handled. Nothing in
 * the toolkit installs signal handlers, so nothing else competes for these.
 *
 * Known gaps, accepted for a bring-up tool: vsnprintf and dladdr are not
 * formally async-signal-safe (dladdr takes dyld's lock), and Darwin allocates
 * __thread storage lazily, so reading the guest registers on a thread that
 * never touched them can malloc. The Windows VEH has the same exposure with
 * fprintf. */

/* PC of the faulting instruction, from the signal context. */
static void *host_fault_pc(void *ucv)
{
    ucontext_t *uc = (ucontext_t *)ucv;
#if defined(__APPLE__) && defined(__aarch64__)
    return (void *)(uintptr_t)uc->uc_mcontext->__ss.__pc;
#elif defined(__APPLE__) && defined(__x86_64__)
    return (void *)(uintptr_t)uc->uc_mcontext->__ss.__rip;
#elif defined(__linux__) && defined(__aarch64__)
    return (void *)(uintptr_t)uc->uc_mcontext.pc;
#else
    (void)uc;
    return NULL;
#endif
}

/* Read or write, when the host can tell.
 *
 * arm64 Darwin: the ESR's WnR bit (6) means "write", but only for a data
 * abort (exception class 0x24 from a lower EL, 0x25 from the same EL). For any
 * other class the bit means something else, so say unknown. */
static int host_fault_access(void *ucv)
{
#if defined(__APPLE__) && defined(__aarch64__)
    ucontext_t *uc = (ucontext_t *)ucv;
    uint32_t esr = uc->uc_mcontext->__es.__esr;
    uint32_t ec = esr >> 26;

    if (ec == 0x24 || ec == 0x25)
        return (esr >> 6) & 1 ? FAULT_WRITE : FAULT_READ;
    return FAULT_UNKNOWN;
#else
    (void)ucv;
    return FAULT_UNKNOWN;
#endif
}

/* The native call chain, innermost first, by walking frame records.
 *
 * Apple's arm64 ABI keeps a frame pointer, so starting from the signal context
 * this is exact and async-signal-safe (bar dladdr) -- unlike backtrace(),
 * which drops the faulting leaf frame. Frame 0 is the faulting PC; frame 1 is
 * lr, which is the caller even when the leaf never built a frame of its own;
 * then each frame record [fp] = caller's fp, [fp+8] = return address. */
static void print_native_stack(void *ucv)
{
#if defined(__APPLE__) && defined(__aarch64__)
    ucontext_t *uc = (ucontext_t *)ucv;
    uintptr_t pc = (uintptr_t)uc->uc_mcontext->__ss.__pc;
    uintptr_t lr = (uintptr_t)uc->uc_mcontext->__ss.__lr;
    uintptr_t fp = (uintptr_t)uc->uc_mcontext->__ss.__fp;
    char name[300];
    int n = 0, first = 1;

    crash_printf("  Native stack (innermost first):\n");
    host_symbol_for((void *)pc, name, sizeof(name));
    crash_printf("    [%d] 0x%llX in %s\n", n++, (unsigned long long)pc, name);
    host_symbol_for((void *)lr, name, sizeof(name));
    crash_printf("    [%d] 0x%llX in %s\n", n++, (unsigned long long)lr, name);

    while (n < 16 && fp && (fp & 7) == 0) {
        uintptr_t next = ((const uintptr_t *)fp)[0];
        uintptr_t ret = ((const uintptr_t *)fp)[1];

        /* A leaf that did build a frame stored lr in it: skip that one
         * repeat only -- recursive frames legitimately share a return address. */
        if (!(first && ret == lr) && ret) {
            host_symbol_for((void *)ret, name, sizeof(name));
            crash_printf("    [%d] 0x%llX in %s\n", n++,
                         (unsigned long long)ret, name);
        }
        first = 0;
        if (next <= fp)     /* the stack grows down: callers' frames are higher */
            break;
        fp = next;
    }
#else
    (void)ucv;
    crash_printf("  Native stack: not available on this host\n");
#endif
}

/* Re-entry guard: a fault while writing the report must end the process, not
 * report again. SA_NODEFER lets a same-signal fault inside the handler get
 * here instead of being force-killed by the kernel with nothing said. */
static volatile sig_atomic_t g_in_crash_handler;

static void restore_default(int sig)
{
    struct sigaction sa;

    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = SIG_DFL;
    sigemptyset(&sa.sa_mask);
    sigaction(sig, &sa, NULL);
}

#if defined(HOST_MMIO_POSIX)
typedef struct MCPXAPUState MCPXAPUState;
extern MCPXAPUState *mcpx_apu_init_standalone(uint8_t *ram_ptr);
extern MCPXAPUState *g_apu_state;
#endif

static void posix_crash_handler(int sig, siginfo_t *si, void *ucv)
{
#if defined(HOST_MMIO_POSIX)
    /* Trapped hardware registers -> their models, through the toolkit's
     * dispatch: the APU, the AC'97 bus-master page (RECOMP_AC97_READY; a write
     * completes the channel reset the title is about to spin on) and the USB
     * OHCI controllers. A serviced access returns here with pc advanced; the
     * kernel resumes the thread after the instruction. */
    if (xbox_PosixMmioFault(ucv, (uintptr_t)si->si_addr))
        return;
#endif
    if (g_in_crash_handler) {
        restore_default(sig);
        return;
    }
    g_in_crash_handler = 1;

    report_fault(host_fault_pc(ucv), (uintptr_t)si->si_addr,
                 host_fault_access(ucv));
    print_native_stack(ucv);

    /* Returning re-executes the faulting instruction with the default
     * disposition in place, so the process dies by the original signal: the
     * shell's exit status and any core dump say what happened. */
    restore_default(sig);
}

/* Alternate signal stack for the boot thread, so a stack overflow there still
 * gets a report. Guest-created threads have none (their start routine is
 * toolkit code), so an overflow on one of those dies unreported -- still by
 * signal. SIGSTKSZ is 128 KB on Darwin; snprintf plus a dladdr per frame does
 * not fit in much less. */
static char g_crash_altstack[SIGSTKSZ];

static void host_install_crash_handler(void)
{
    stack_t ss;
    struct sigaction sa;

    memset(&ss, 0, sizeof(ss));
    ss.ss_sp = g_crash_altstack;
    ss.ss_size = sizeof(g_crash_altstack);
    if (sigaltstack(&ss, NULL) != 0)
        fprintf(stderr, "[BOOT] sigaltstack failed; a boot-thread stack "
                        "overflow will die without a report\n");

    memset(&sa, 0, sizeof(sa));
    sa.sa_sigaction = posix_crash_handler;
    sa.sa_flags = SA_SIGINFO | SA_ONSTACK | SA_NODEFER;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGBUS, &sa, NULL);
    sigaction(SIGSEGV, &sa, NULL);
}

/* ── POSIX: on-demand dump of every thread (RECOMP_THREAD_DUMP) ─ */

/* A hang leaves no fault to report, and on macOS neither `sample` nor an lldb
 * attach gets through to this binary. With RECOMP_THREAD_DUMP set, a SIGUSR1
 * (kill -USR1 <pid>) prints the native stack of every thread instead. Lifted
 * calls are native calls, so each stack reads as the guest call chain: the
 * sub_XXXXXXXX frames are guest functions, innermost first.
 *
 * The signal only wakes a dedicated thread blocked in sigwait; the dump runs
 * there, as ordinary code, with each other thread suspended while its frame
 * records are walked. Apple arm64 only (frame pointers are guaranteed there).
 * Known gap: dladdr takes dyld's lock, so a thread suspended while holding it
 * would hang the dump. */
#if defined(__APPLE__) && defined(__aarch64__)
#include <mach/mach.h>
#include <pthread.h>

#define MEM32_HOST(va) \
    (*(volatile uint32_t *)((uintptr_t)g_xbox_mem_offset + (uint32_t)(va)))

static void dump_one_thread(thread_act_t th, int idx)
{
    arm_thread_state64_t st;
    mach_msg_type_number_t cnt = ARM_THREAD_STATE64_COUNT;
    char name[300];
    uintptr_t pc, lr, fp;
    int n = 0;

    if (thread_get_state(th, ARM_THREAD_STATE64, (thread_state_t)&st,
                         &cnt) != KERN_SUCCESS) {
        crash_printf("[DUMP] thread %d: state unavailable\n", idx);
        return;
    }
    pc = (uintptr_t)arm_thread_state64_get_pc(st);
    lr = (uintptr_t)arm_thread_state64_get_lr(st);
    fp = (uintptr_t)arm_thread_state64_get_fp(st);

    crash_printf("[DUMP] thread %d (mach port 0x%x):\n", idx, (unsigned)th);
    host_symbol_for((void *)pc, name, sizeof(name));
    crash_printf("    [%d] %s\n", n++, name);
    host_symbol_for((void *)lr, name, sizeof(name));
    crash_printf("    [%d] %s (lr)\n", n++, name);
    while (n < 48 && fp && (fp & 7) == 0) {
        uintptr_t next = ((const uintptr_t *)fp)[0];
        uintptr_t ret = ((const uintptr_t *)fp)[1];

        if (ret) {
            host_symbol_for((void *)ret, name, sizeof(name));
            crash_printf("    [%d] %s\n", n++, name);
        }
        if (next <= fp)
            break;
        fp = next;
    }
}

static void dump_all_threads(void)
{
    thread_act_array_t threads;
    mach_msg_type_number_t count, i;
    thread_act_t self = mach_thread_self();

    if (task_threads(mach_task_self(), &threads, &count) != KERN_SUCCESS)
        return;
    crash_printf("[DUMP] %u threads\n", (unsigned)count);
    /* BLiNX 2: the D3D device (0x2F1FB8) and the pushbuffer-space wait in
     * sub_002E8110, which spins on *[device+0x30] against [device+0x2C]. */
    if (g_xbox_mem_offset) {
        uint32_t dev = MEM32_HOST(0x2F1FB8);
        if (dev && dev + 0x40 <= g_xbox_total_ram) {
            uint32_t p30 = MEM32_HOST(dev + 0x30);
            crash_printf("[DUMP] d3d device 0x%08X: +0x2C=0x%08X +0x30=0x%08X\n",
                         dev, MEM32_HOST(dev + 0x2C), p30);
            crash_printf("[DUMP]   *(+0x30)=0x%08X\n", MEM32_HOST(p30));
        }
    }
    for (i = 0; i < count; i++) {
        if (threads[i] == self)
            continue;
        if (thread_suspend(threads[i]) != KERN_SUCCESS)
            continue;
        dump_one_thread(threads[i], (int)i);
        thread_resume(threads[i]);
    }
    for (i = 0; i < count; i++)
        mach_port_deallocate(mach_task_self(), threads[i]);
    vm_deallocate(mach_task_self(), (vm_address_t)threads,
                  count * sizeof(*threads));
    mach_port_deallocate(mach_task_self(), self);
}

static void *thread_dump_main(void *arg)
{
    sigset_t *set = (sigset_t *)arg;
    int sig;

    for (;;)
        if (sigwait(set, &sig) == 0)
            dump_all_threads();
    return NULL;
}

static void host_install_thread_dump(void)
{
    static sigset_t set;
    pthread_t t;

    if (!recomp_env(RENV_THREAD_DUMP))
        return;
    /* Block SIGUSR1 here, before any other thread exists, so every thread
     * inherits the mask and only the sigwait thread ever takes it. */
    sigemptyset(&set);
    sigaddset(&set, SIGUSR1);
    pthread_sigmask(SIG_BLOCK, &set, NULL);
    if (pthread_create(&t, NULL, thread_dump_main, &set) == 0) {
        pthread_detach(t);
        fprintf(stderr, "[BOOT] thread_dump: kill -USR1 %d dumps "
                        "every thread\n", (int)getpid());
    }
}
#else
static void host_install_thread_dump(void) {}
#endif

#endif /* _WIN32 */

/* ── RECOMP_MEM_DUMP ───────────────────────────────────────────
 *
 * RECOMP_MEM_DUMP=<guest addr>,<bytes>,<path prefix> with
 * RECOMP_MEM_DUMP_EVERY=<seconds> (default 20): a thread writes that range
 * of guest memory to <prefix>_<n>.bin every interval, so a texture or table
 * can be looked at offline from the moment it holds what a frame used.
 * Debug only; off unless set. */
#if !defined(_WIN32)
#include <pthread.h>
static uint32_t s_md_addr, s_md_len, s_md_every;
static char     s_md_pre[256];

static void *mem_dump_main(void *arg)
{
    unsigned n = 0;
    (void)arg;
    for (;;) {
        char path[300];
        FILE *f;
        sleep(s_md_every);
        snprintf(path, sizeof path, "%s_%03u.bin", s_md_pre, n++);
        f = fopen(path, "wb");
        if (!f)
            continue;
        fwrite((const uint8_t *)(uintptr_t)xbox_GetMemoryOffset() + s_md_addr, 1,
               s_md_len, f);
        fclose(f);
        fprintf(stderr, "[MEMDUMP] %s: 0x%08X + 0x%X\n", path, s_md_addr, s_md_len);
    }
    return NULL;
}

static void host_install_mem_dump(void)
{
    const char *e = recomp_env(RENV_MEM_DUMP), *ev = recomp_env(RENV_MEM_DUMP_EVERY);
    pthread_t t;
    char *q;
    if (!e)
        return;
    s_md_addr = (uint32_t)strtoul(e, &q, 0);
    if (*q++ != ',')
        return;
    s_md_len = (uint32_t)strtoul(q, &q, 0);
    if (*q++ != ',' || !*q || !s_md_len)
        return;
    snprintf(s_md_pre, sizeof s_md_pre, "%s", q);
    s_md_every = ev ? (uint32_t)atoi(ev) : 20u;
    if (!s_md_every)
        s_md_every = 20;
    if (pthread_create(&t, NULL, mem_dump_main, NULL) == 0)
        pthread_detach(t);
}
#else
static void host_install_mem_dump(void) {}
#endif

/* ── Startup failures ──────────────────────────────────────── */

/* A required startup step failed: say which, and what to do, on stderr on
 * every host -- and in a dialog on Windows, where a GUI-subsystem launch may
 * have no console to read. */
static void host_report_fatal(const char *step, const char *detail)
{
    fprintf(stderr, "[FATAL] %s: %s\n", step, detail);
    fflush(stderr);
#if defined(_WIN32)
    MessageBoxA(NULL, detail, "Recomp", MB_ICONERROR);
#endif
}

/* ── Boot sequence (shared) ────────────────────────────────── */

static int host_main(void)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    /* RECOMP_STDIO_LOG=<path>: send stdout and stderr to a file (truncated).
     * Proton drops a game's stdio whatever its subsystem, so this is the only
     * way to see the boot log and crash reports there. Before anything prints. */
    int stdio_log_err = -1;   /* Windows only: did stderr reopen? */
    {
        const char *stdio_log = recomp_env(RENV_STDIO_LOG);
        if (stdio_log && *stdio_log) {
#if defined(_WIN32)
            /* A GUI-subsystem exe starts with no stderr descriptor
             * (_fileno(stderr) == -2), so there is nothing to _dup2 onto.
             * Reopen both streams instead, in append mode so that their
             * writes interleave rather than overwrite each other. */
            FILE *trunc = fopen(stdio_log, "w");
            if (trunc) fclose(trunc);
            if (freopen(stdio_log, "a", stdout))
                stdio_log_err = freopen(stdio_log, "a", stderr) != NULL;
#else
            if (freopen(stdio_log, "w", stdout))
                dup2(fileno(stdout), fileno(stderr));
#endif
        }
    }

    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
    if (stdio_log_err >= 0)
        printf("[BOOT] RECOMP_STDIO_LOG: stderr %s\n",
               stdio_log_err ? "redirected" : "NOT redirected");
    /* Deprecated names and bad keys found when the environment was read:
     * held until now, so they land in the log rather than a closed stderr. */
    recomp_env_flush_notes();

    printf("=== BLiNX 2 - Static Recompilation ===\n");
    printf("Loading XBE...\n");
    xbox_log_thread_role("guest-main", 0);

    /* Step 1: Crash diagnostics, before anything can fault */
    host_install_crash_handler();
    host_install_thread_dump();

    /* Step 2: Load XBE */
    if (!load_xbe(BLINX2_XBE_PATH, &xbe_data, &xbe_size)) {
        host_report_fatal("load XBE",
            "cannot read " BLINX2_XBE_PATH " (relative to the current "
            "directory). Run from the project root, with the game files in "
            BLINX2_GAME_DIR "/.");
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* RECOMP_AC97_READY (default on) needs MMIO trapping: recomp_env turns
     * it off on hosts that cannot service it, saying so if it was asked for,
     * because MemoryLayoutInit would otherwise mark the APU page PROT_NONE
     * with nothing to answer the faults. */

    /* Step 3: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    /* Deliberate deviation from retail (64 MB): devkit RAM. All 73 XBE
     * sections are loaded at boot, including the 49 that are not preload and
     * that XeLoadSection pages in and out on hardware -- that paging is not
     * modeled -- so at 64 MB the heap is ~14 MB and the game fills it during
     * its first archive loads. See openspec change xdk-library-hle. At 128 MB
     * the RAM mirrors must stop short of the contig window at 0x80000000; on
     * Windows that is the toolkit's reservation path (proton/win-layout). */
    xbox_SetTotalRam(XBOX_DEVKIT_RAM);
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        host_report_fatal("map Xbox memory layout",
            "failed to initialize the Xbox memory layout. The required "
            "virtual address range may be unavailable.");
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);
    host_install_mem_dump();

    /* D3D's GPU completion fence. The device pointer is at 0x2F1FB8. The
     * device holds the last fence it submitted at +0x2C and, at +0x30, a
     * pointer to the word the GPU writes as it completes work (contiguous
     * memory, 0x80000000 in practice). The fence wait in sub_002E8110
     * spins until that word catches up.
     *
     * With RECOMP_PB_EXEC the toolkit's pushbuffer executor writes that word
     * itself when it reaches NV097_BACK_END_WRITE_SEMAPHORE_RELEASE (D3D
     * points the semaphore at offset 0 of the contiguous window, i.e. at
     * 0x80000000), and this mirror steps aside after the first release.
     * It stays registered as the fallback: with the executor off nothing
     * consumes the pushbuffer, so mirroring submitted -> completed, as the
     * toolkit does for Wreckless, is the only way the wait can end. Without
     * either, the main thread hangs there after the archive load (the word
     * stays 0xDEADBEEF). See openspec change present-frames. */
    xbox_Nv2aMirrorFence(0x2F1FB8, 0x2C, 0x30);

    /* The vblank interrupt, which the toolkit only raises on request. The
     * main loop (sub_0005F960 at 0x00060475) waits for the frame counter at
     * 0xAE7388 to move. Only the callback the title registers through
     * D3DDevice_SetVerticalBlankCallback (sub_000604A0) moves it, and D3D's
     * vblank DPC calls that callback. Without the interrupt the loop spins
     * forever. An explicit RECOMP_VBLANK in the environment still wins. */
    if (!recomp_env(RENV_VBLANK))
        recomp_env_set(RENV_VBLANK, "1");

#if HOST_CAN_SERVICE_MMIO
    /* Step 4: Bring up the emulated APU.
     *
     * Gated on the same variable that unmaps its registers, because the two
     * halves are useless apart: a trap with no model declines every access,
     * and a model nothing traps into never sees a register. The APU walks
     * Xbox physical RAM to find voice buffers, so it gets the guest RAM
     * base. */
    if (recomp_env(RENV_AC97_READY)) {
        g_apu_state = mcpx_apu_init_standalone((uint8_t *)xbox_GetMemoryBase());
        fprintf(stderr, "[BOOT] emulated APU %s\n",
                g_apu_state ? "up" : "FAILED to initialise");
        /* Its interrupt (audio task 4.7) and the contiguous window are the
         * toolkit's: the APU frame thread delivers vector 5 itself. */
        /* Diagnostic: the cost of one trapped APU access (audio spike 1.4). */
        if (g_apu_state && recomp_env(RENV_APU_FAULT_BENCH)) {
            extern double apu_hook_fault_bench(unsigned n);
            apu_hook_fault_bench((unsigned)atoi(recomp_env(RENV_APU_FAULT_BENCH)));
        }
    }
#endif

    /* Step 5: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 6: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(BLINX2_GAME_DIR, NULL);
    }

    /* Step 7: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 8: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /* Skip XAPI's utility-drive mount (XBE init flag XINIT_MOUNT_UTILITY_DRIVE).
     *
     * With the flag set, XapiInitProcess calls XMountUtilityDrive, which opens
     * the raw disk \Device\Harddisk0\partition0 to read the partition table.
     * The toolkit backs that device with an image file on Windows only (and
     * none ships with the game); on POSIX the path is unrecognized, the open fails, and XAPI boots to the
     * dashboard with XLD_ERROR_INVALID_HARD_DISK before the game starts.
     * Z:\ needs no mount here -- the path layer maps it to the save Cache
     * directory regardless. The header is in guest memory, which is where
     * XAPI reads the flags from.
     *
     * Cleared on every host, Windows too: one boot path everywhere, and
     * Proton is not left as the only host exercising the untested
     * Partition0.img route. */
    {
        volatile uint32_t *init_flags =
            (volatile uint32_t *)((uint8_t *)g_xbox_mem_offset + 0x00010124u);
        if (*init_flags & 1u) {
            *init_flags &= ~1u;
            printf("[BOOT] XBE init flag MOUNT_UTILITY_DRIVE cleared "
                   "(no raw-disk mount)\n");
        }
    }

    /*
     * No CRT globals are pre-initialized: BLiNX 2's CRT heap init (__heap_init,
     * __active_heap) runs as recompiled and needs no help from the host.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", BLINX2_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over the
     * whole function table -- roughly log2(n) branches on *every*
     * indirect call, which for a 45,000-function C++ title is about 16
     * every time the game goes through a vtable. Half-Life 2 spent most
     * of its static initialisation inside recomp_lookup for exactly this
     * reason, and it read as a hang.
     *
     * Optional by design: if the allocation fails the search still works,
     * so a failure is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    /* Arm the hang watchdog. Does nothing unless RECOMP_WATCHDOG_SECS is set,
     * and must be called from this thread -- the guest registers it samples are
     * thread-local, so it has to be handed the copies belonging to the thread
     * that runs guest code.
     *
     * Not optional boilerplate: without this call RECOMP_WATCHDOG_SECS is
     * silently inert, and the one diagnostic that tells a hang from slowness
     * does nothing while appearing to be set. */
    xbox_WatchdogStart();

    { extern void cat_save_seed(void); cat_save_seed(); }   /* RECOMP_SAVE_SEED into RECOMP_SAVE_DIR */
    { extern void cat_pad_early_init(void); cat_pad_early_init(); } /* scripted pad: see file opens */

    /* Step 9: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* ── Entry points ──────────────────────────────────────────── */

#if defined(_WIN32)
/* The Windows build links as a GUI-subsystem program, which starts here. */
int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;
    recomp_env_init();   /* the environment, read once, before any thread */
    xbox_log_thread_role("process-main", 0);
    xbox_HostWindowSetTitle("BLiNX 2 (recomp)");
    return host_main();
}
#endif

/* Console entry point: every non-Windows host, and console builds on Windows
 * (for debugging -- lets you see printf output).
 *
 * POSIX: the process main thread belongs to the window. AppKit only runs its
 * event loop there, so xbox_HostWindowMain (toolkit fb_present_sdl.c) opens
 * an SDL window here and runs host_main -- the whole boot and the guest --
 * on a "guest-main" pthread. The crash handler's alternate stack and the
 * watchdog are set up inside host_main, so they follow the guest onto that
 * thread. RECOMP_HEADLESS=1 keeps the guest on this thread, as before. */

int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    /* The initial thread, named first: the toolkit leaves its OS name alone
     * (renaming it breaks pgrep/ps). host_main then logs guest-main, on this
     * thread when headless or on Windows, on its own pthread when windowed. */
    recomp_env_init();   /* the environment, read once, before any thread */
    xbox_log_thread_role("process-main", 0);
    xbox_HostWindowSetTitle("BLiNX 2 (recomp)");
#if defined(_WIN32)
    return host_main();
#else
#if defined(__APPLE__) && defined(__aarch64__)
    /* RECOMP_THREAD_DUMP waits for SIGUSR1 on a thread of its own and blocks
     * it on the thread that installs it (now the guest's). Block it here as
     * well, before any thread exists, or it lands on the window thread and
     * the default action kills the process. Only where that dumper exists
     * (host_install_thread_dump): elsewhere a blocked SIGUSR1 would pend
     * forever instead of acting. */
    if (recomp_env(RENV_THREAD_DUMP)) {
        sigset_t set;
        sigemptyset(&set);
        sigaddset(&set, SIGUSR1);
        pthread_sigmask(SIG_BLOCK, &set, NULL);
    }
#endif
    return xbox_HostWindowMain(host_main);
#endif
}
